### ISSUE TITLE
Cannot Save Render Engine Preset Settings

### ISSUE THREAD

**Issue by EnfixingLight** [NevilArt/BsMax_2_80#16]
Hello,

I'm having an issue with saving my preset render settings for Eevee. When I try to save them, I get this error: 

Python: Traceback (most recent call last):
  File "C:\Users\tstri\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BsMax_2_80-master\tools\internal\render\preset.py", line 189, in execute
    self.save_file(create_preset_script(ctx))
  File "C:\Users\tstri\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BsMax_2_80-master\tools\internal\render\preset.py", line 178, in save_file
    mkdir(preset_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tstri\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\presets\\BsMax\\render\\'

location: <unknown location>:-1

Please help.

Thank you,
Thomas

**Comment by NevilArt** [comment]
Hi.

I did a little fix on code.
Please check the last update and let me know is the problem solved or not?.

Thank you for report the issue.

**Comment by EnfixingLight** [comment]
Thank you for working on this. I'm still getting an error I'm afraid.

Python: Traceback (most recent call last):
  File "C:\Users\tstri\AppData\Roaming\Blender
Foundation\Blender\2.93\scripts\addons\BsMax_2_80-master\tools\internal\render\preset.py",
line 193, in execute
    self.save_file(create_preset_script(ctx))
  File "C:\Users\tstri\AppData\Roaming\Blender
Foundation\Blender\2.93\scripts\addons\BsMax_2_80-master\tools\internal\render\preset.py",
line 181, in save_file
    if os.access(preset_path, os.W_OK):
NameError: name 'os' is not defined

location: <unknown location>:-1

**Comment by NevilArt** [comment]
Looks like I did a mistake. check the new updated one now. but I`m not sure the problem has solved or not yet.
