### ISSUE TITLE
Can not activate BsMax.

### ISSUE THREAD

**Issue by hansnolte** [NevilArt/BsMax_2_80#17]
Hi NevilArt,

unfortunately I can no longer activate your great plugin.

`Traceback (most recent call last):

File "E:\Blender\3.0\scripts\addons\BsMax\__init__.py", line 46, in <module> from .tools import register_tools, unregister_tools
File "E:\Blender\3.0\scripts\addons\BsMax\tools\__init__.py", line 17, in <module> from .internal import register_internal, unregister_internal
File "E:\Blender\3.0\scripts\addons\BsMax\tools\internal\__init__.py", line 27, in <module> from .render import register_render,unregister_render
File "E:\Blender\3.0\scripts\addons\BsMax\tools\internal\render\__init__.py", line 19, in <module> from .preset import register_preset, unregister_preset
File "E:\Blender\3.0\scripts\addons\BsMax\tools\internal\render\preset.py", line 22, in <module> preset_path = bpy.utils.user_resource('SCRIPTS', "presets") + "\\BsMax\\render\\"
TypeError: user_resource() takes 1 positional argument but 2 were given`

Win 10
Blender - June 16, 03:26:25 - 4891da8ae225 - x64

Many greetings
Hans

**Comment by NevilArt** [comment]
Hi dear Hansnolte.

Thank you for letting me know this issue. I made some changes and I hope the problem has solved. Can you test this version and let me know is the problem solved or not?
[BsMax_2_80.zip](https://github.com/NevilArt/BsMax_2_80/files/6680900/BsMax_2_80.zip)

**Comment by hansnolte** [comment]
Hi NevilArt,

thanks for the update, but unfortunately it still does not work.

I tested with Blender from today. June 20, 02:23:13 - 3da25dc625c8

`Exception in module register(): E:\Blender\3.0\scripts\addons\BsMax\__init__.py

Traceback (most recent call last):
File "E:\Blender\3.0\scripts\modules\addon_utils.py", line 386, in enable mod.register()
File "E:\Blender\3.0\scripts\addons\BsMax\__init__.py", line 360, in register load_preferences(preferences)
File "E:\Blender\3.0\scripts\addons\BsMax\__init__.py", line 324, in load_preferences filename = bpy.utils.user_resource('SCRIPTS', 'addons') + '/BsMax.ini'
TypeError: user_resource() takes 1 positional argument but 2 were given`

Many greetings
Hans

**Comment by NevilArt** [comment]
looks like that problem solved. this one is another one. Good. I fix that too.
[BsMax_2_80.zip](https://github.com/NevilArt/BsMax_2_80/files/6682596/BsMax_2_80.zip)
check this one and let me know is it works or not.

**Comment by hansnolte** [comment]
Great Work NevilArt!

It works obsolutly smooth.

Many thanks
Hans

**Comment by NevilArt** [comment]
Good. thank you for report :)
