### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by tonycstech** [NevilArt/BsMax_2_80#8]
#1 How to load it ?
#2 I tried to import __init__.py and it gave me errors.
Traceback (most recent call last):
  File "P:\Blender\2.90\scripts\modules\bpy\utils\__init__.py", line 645, in keyconfig_set
    execfile(filepath)
  File "P:\Blender\2.90\scripts\modules\bpy\utils\__init__.py", line 90, in execfile
    mod_spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\presets\keyconfig\__init__.py", line 42, in <module>
    from .keymaps import register_keymaps,unregister_keymaps
ModuleNotFoundError: No module named '__main__.keymaps'; '__main__' is not a package

#3 I tried to import max.py and it gave me errors
Traceback (most recent call last):
  File "P:\Blender\2.90\scripts\modules\bpy\utils\__init__.py", line 645, in keyconfig_set
    execfile(filepath)
  File "P:\Blender\2.90\scripts\modules\bpy\utils\__init__.py", line 90, in execfile
    mod_spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\presets\keyconfig\max.py", line 17, in <module>
    from bsmax.keymaps import KeyMaps
ModuleNotFoundError: No module named 'bsmax'

**Comment by NevilArt** [comment]
Hi
you have to download all the package. click on the green code button and "download zip", do not extract the zip file. in blender got to Edit/Prefrences/add-ons/inistal.. and select the BsMax_2_80_master.zip, Then choose 3Ds Max.

**Comment by tonycstech** [comment]
That should be in the read me file at the top.
Thanks.

**Comment by NevilArt** [comment]
Yeah you are right. Thank you for suggestion.

**Comment by tonycstech** [comment]
W opens object context menu instead of activating MOVE command.
When dragging and pressing S to snap, it turns into scale instead of
activating SNAP while dragging.
Shift S Drag does not duplicate.
Those are just the few fundamental problems.
Is there a way to activate all snap modes at once ?

**Comment by NevilArt** [comment]
Some times need to reopen Blender to make add-on  works properly, 'W' most work correctly then.
Pressing S or A while dragging and switch navigation type without releasing the middle mouse button are known issues but because of API limitation not solved, recently key-map gesture API updated I had to try it again.
About Snap, in blender is only one snap operator that handles all kinds (move, rotate, scale) by different options. but in max that was 3 different operators for now I had no idea how can I solve this. in time I hope find solution for this things.

If you have any Idea or suggestion feel free and share with me. thank you.
